# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

host: 0.0.0.0

title: "LibRML"
tagline: "Library Rights Machine-readable Language"
description: "LibRML ist ein auf Kulturerbeeinrichtungen angepasstes Modell zur Beschreibung maschineninterpretierbarer Berechtigungen und Beschränkungen für spezifische Nutzungsarten digitaler Objekte."
url: "https://librml.org"

lang: "de"
timezone: "Europe/Berlin"

email: librml@slub-dresden.de

author:
  name: "SLUB Dresden"
  type: "Organization"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
